run:
  timeout: 2m
  build-tags: "${BUILD_TAG}"

linters:
  enable:
    - gofmt
    - unconvert
    - unparam
    - asciicheck
    - misspell
    - revive
    - decorder
    - reassign
    - usestdlibvars
    - nilerr
    - gosec
    - exportloopref
    - whitespace
    - gocyclo
    - nestif
    - gochecknoinits
    - gocognit
    - funlen
    - forbidigo
    - godox
    - gocritic
    - gci
    - lll

fix: true

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - lll
        - gocognit
